project: default
source:
  repoURL: 'https://github.com/krakozja/ArgoCD'
  path: frontend
  targetRevision: main
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated: {}
